name: herbie
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - curl
  - toml
  - requests
  - numpy
  - matplotlib
  - cartopy
  - jupyter
  - jupyterlab
  - netcdf4
  - pandas
  - geopandas
  - scipy
  - metpy
  - xarray
  - pyproj
  - h5py
  - pygrib
  - cfgrib
  - pylint
  - s3fs
  - zarr
  - wgrib2  # ONLY AVAILABLE ON LINUX. Comment if not using Linux.

  - pip:
    # Development Version from GitHub
    - git+https://github.com/blaylockbk/Herbie.git
    # *or* the latest release from PyPI
    #- hrrrb    # Release Version

    # Borrow some tools from my garage
    - git+https://github.com/blaylockbk/Carpenter_Workshop.git  
