name: herbie
channels:
  - conda-forge
dependencies:
  - python>=3.10
  - pip
  - rclone # Not used by Herbie, useful if you are downloading data (https://rclone.org/)

  - herbie-data

  #==============
  # Dependencies
  #==============
  - curl
  - cartopy>=0.20.3
  - cfgrib>=0.9.10.1
  - eccodes
  - geos
  - matplotlib>=3.5.3
  - metpy
  - numpy
  - pandas
  - proj
  - pygrib
  - requests
  - toml
  #- wgrib2 # ONLY AVAILABLE ON LINUX. Uncomment if you want this optional dependency.
  - xarray>=2022.6.0

  - jupyter
  - jupyterlab

  - pip:
      # Borrow some tools from my garage
      - git+https://github.com/blaylockbk/Carpenter_Workshop.git

#==============================================================================
#                               Notes
#==============================================================================
# Being more specific with versions *may* help speed up conda
# creating/updating environments
# https://www.anaconda.com/blog/understanding-and-improving-condas-performance



# =============================================================================
#                              Conda Tips
# =============================================================================
# To create this environment
#
#     curl -O https://raw.githubusercontent.com/blaylockbk/Herbie/main/environment.yml
#     conda env create -f environment.yml
#
# To update this environment
#
#     conda env update -f environment.yml --prune
#
# To remove this environment
#
#     conda env remove --name herbie
#
# To do a conda clean
#
#     conda clean -tp
# =============================================================================
