name: herbie
channels:
  - conda-forge
dependencies:
  - python=3.8
  - curl
  - requests
  - numpy
  - matplotlib
  - cartopy
  - jupyter
  - jupyterlab
  - netcdf4
  - pandas
  - scipy
  - metpy
  - siphon
  - xarray
  - pyproj
  - h5py
  - pygrib
  - cfgrib
  - pylint
  - s3fs
  - zarr
  #- wgrib2  # Uncomment if you are on a Linux machine

  - pip:
    # Development Version from GitHub
    - git+https://github.com/blaylockbk/HRRR_archive_download.git
    # *or* the latest release from PyPI
    #- hrrrb    # Release Version

    # Do you need to borrow my hammer?
    - git+https://github.com/blaylockbk/Carpenter_Workshop.git  
