# Note:
# More specific versions *may* help speed up conda creating/updating environments
# https://www.anaconda.com/blog/understanding-and-improving-condas-performance

name: herbie
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - git
  - curl
  #- wgrib2  # ONLY AVAILABLE ON LINUX. Comment if not using Linux.

  # Tools
  # -----
  - cartopy
  - cfgrib=0.9.9.1
  - geopandas
  - h5py
  - jupyter
  - jupyterlab
  - matplotlib
  - metpy
  - netcdf4
  - numpy>=1.22.3
  - pandas>=1.4.1
  - pygrib
  - pylint
  - pyproj
  - requests
  - s3fs
  - scipy
  - toml
  - xarray
  - zarr

  # Formatter & Testing
  # -------------------
  - black
  - jupyterlab_code_formatter
  - isort
  - pylint
  - pytest
  - line_profiler

  # Documentation
  # -------------
  - sphinx>=4.4.0
  - nbsphinx
  - pydata-sphinx-theme # PyData Sphinx Theme (i.e, Numpy, Pandas, MetPy)
  - sphinx-panels # Add bootstrap elements to Sphinx
  - recommonmark
  - sphinx-markdown-tables
  - sphinxcontrib-mermaid # For mermaid diagram support
  - autodocsumm
  - sphinx-autosummary-accessors # pandas and xarray accessor docs
  - latexmk
  - myst-parser
  - linkify-it-py

  - pip:
      # Development Version from GitHub
      - git+https://github.com/blaylockbk/Herbie.git
      # *or* the latest release from PyPI
      #- herbie-data    # Release Version

      # Borrow some tools from my garage
      - git+https://github.com/blaylockbk/Carpenter_Workshop.git
