name: hrrrb
channels:
  - conda-forge
dependencies:
  - python=3.8
  - curl
  - numpy
  - matplotlib
  - cartopy
  - requests
  - jupyter
  - jupyterlab
  - netcdf4
  - pandas
  - scipy
  - metpy
  - siphon
  - xarray
  - pyproj
  - h5py
  - pygrib
  - cfgrib
  - pylint
  - s3fs
  - zarr
  #- wgrib2  # Uncomment if you are on a Linux machine

  - pip:
    # Development Version from GitHub
    - git+https://github.com/blaylockbk/HRRR_archive_download.git
    - git+https://github.com/blaylockbk/Carpenter_Workshop.git  # "Can I borrow your hammer?"
    
    # *or* the latest release from PyPI
    #- hrrrb    # Release Version
